#!/bin/sh

#delete old version of shiftfs with dkms

#functions:

dkms_remove () {
dkms remove -m shiftfs -v $MODVERNOW --all
rm installed-version.txt
}

version_check () {
#read out installed version
if [ -e installed-version.txt ]; then
MODVERNOW=$(cat installed-version.txt)
dkms_remove
else
echo '"installed-version.txt" is missing.'
echo 'You can add it manually, but you need to know the right version number (e.g. "1.0").'
echo 'Take a look at CHANGELOG or search for the shiftfs folder in "/usr/src/" .'
echo 'The number in the folder name, e.g. "shiftfs-1.0", is the version number.'
fi
}

#####
#Start of script

#read username
USERNAME=$(whoami)

#check if run as root
if [ $USERNAME != root ]; then
echo 'You need to run this script as root or with sudo.'  
else 
version_check   
exit    
fi








